USE hospital_db;


-- Add some views for common queries
CREATE OR REPLACE VIEW vw_pacientes_internados AS
SELECT p.ID_PACIENTE, p.NOME, p.CPF, q.NUMERO AS QUARTO_NUMERO, q.TIPO AS QUARTO_TIPO, e.DATA_ENTRADA
FROM PACIENTE p
JOIN ESTADIA e ON p.ID_PACIENTE = e.ID_PACIENTE
JOIN QUARTO q ON e.ID_QUARTO = q.ID_QUARTO
WHERE p.STATUS = 'Internado' AND e.DATA_SAIDA IS NULL;

CREATE OR REPLACE VIEW vw_faturas_pendentes AS
SELECT f.ID_FATURA, p.NOME AS PACIENTE, f.VALOR_TOTAL, f.DATA_EMISSAO, mp.TIPO AS METODO_PAGAMENTO
FROM FATURA f
JOIN ESTADIA e ON f.ID_ESTADIA = e.ID_ESTADIA
JOIN PACIENTE p ON e.ID_PACIENTE = p.ID_PACIENTE
JOIN METODO_PAGAMENTO mp ON f.ID_METODO_PAGAMENTO = mp.ID_METODO_PAGAMENTO
WHERE f.STATUS_PAGAMENTO = 'Pendente';

CREATE OR REPLACE VIEW vw_pedidos_por_status AS
SELECT pe.ID_PEDIDO, pa.NOME AS PACIENTE, q.NUMERO AS QUARTO, pe.STATUS, pe.DATA_PEDIDO, c.NOME AS CAMAREIRA
FROM PEDIDO pe
JOIN ESTADIA e ON pe.ID_ESTADIA = e.ID_ESTADIA
JOIN PACIENTE pa ON e.ID_PACIENTE = pa.ID_PACIENTE
JOIN QUARTO q ON e.ID_QUARTO = q.ID_QUARTO
JOIN CAMAREIRA c ON pe.ID_CAMAREIRA = c.ID_CAMAREIRA;
